-- TASK 7: INDEXES AND SEQUENCES SCRIPT
-- Target: Oracle 19c+
-- Note: Oracle 12c+ 'GENERATED ALWAYS AS IDENTITY' handles PK sequences automatically.

-- 1. B-Tree & Bitmap Indexes for PATIENT
CREATE INDEX IDX_PATIENT_EMAIL_UPR ON PATIENT(UPPER(email));
CREATE INDEX IDX_PATIENT_NAME_UPR ON PATIENT(UPPER(full_name));
CREATE BITMAP INDEX IDX_PATIENT_GENDER ON PATIENT(gender);
CREATE BITMAP INDEX IDX_PATIENT_BLOOD ON PATIENT(blood_group);

-- 2. Indexes for DOCTOR
CREATE INDEX IDX_DOCTOR_DEPT ON DOCTOR(department_id);
CREATE INDEX IDX_DOCTOR_EMAIL_UPR ON DOCTOR(UPPER(email));
CREATE INDEX IDX_DOCTOR_SPEC ON DOCTOR(specialisation);

-- 3. Indexes for DEPARTMENT
CREATE INDEX IDX_DEPT_HEAD ON DEPARTMENT(head_doctor_id);

-- 4. Indexes for STAFF
CREATE INDEX IDX_STAFF_DEPT ON STAFF(department_id);
CREATE INDEX IDX_STAFF_EMAIL_UPR ON STAFF(UPPER(email));
CREATE BITMAP INDEX IDX_STAFF_ROLE ON STAFF(role);
CREATE BITMAP INDEX IDX_STAFF_SHIFT ON STAFF(shift);

-- 5. Indexes for APPOINTMENT
CREATE INDEX IDX_APPT_PATIENT ON APPOINTMENT(patient_id);
CREATE INDEX IDX_APPT_PATIENT_DATE ON APPOINTMENT(patient_id, appt_date DESC);
CREATE BITMAP INDEX IDX_APPT_STATUS ON APPOINTMENT(status);
-- UQ index created implicitly by constraint UQ_APPOINTMENT_SLOT, 
-- but explicit parameters would be provided in high-performance tuning.

-- 6. Indexes for CONSULTATION
CREATE INDEX IDX_CONS_REF_DOC ON CONSULTATION(referring_doctor_id);

-- 7. Indexes for PRESCRIPTION_ITEM
CREATE INDEX IDX_PRES_ITEM_PRES ON PRESCRIPTION_ITEM(prescription_id);

-- 8. Indexes for BILLING
CREATE BITMAP INDEX IDX_BILLING_PAY_STATUS ON BILLING(payment_status);
CREATE BITMAP INDEX IDX_BILLING_PAY_MODE ON BILLING(payment_mode);

-- 9. Indexes for AUDIT_LOG
CREATE INDEX IDX_AUDIT_TABLE_REC ON AUDIT_LOG(table_name, record_id);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG(changed_at);


-- =========================================================
-- OPTIONAL SCHEMA ALIASING (SYNONYMS)
-- Use these if API application connects through a lower-privileged role like CLINIC_API
-- =========================================================
/*
CREATE PUBLIC SYNONYM DEPARTMENT FOR DEPARTMENT;
CREATE PUBLIC SYNONYM DOCTOR FOR DOCTOR;
CREATE PUBLIC SYNONYM STAFF FOR STAFF;
CREATE PUBLIC SYNONYM PATIENT FOR PATIENT;
CREATE PUBLIC SYNONYM MEDICAL_RECORD FOR MEDICAL_RECORD;
CREATE PUBLIC SYNONYM APPOINTMENT FOR APPOINTMENT;
CREATE PUBLIC SYNONYM CONSULTATION FOR CONSULTATION;
CREATE PUBLIC SYNONYM PRESCRIPTION FOR PRESCRIPTION;
CREATE PUBLIC SYNONYM PRESCRIPTION_ITEM FOR PRESCRIPTION_ITEM;
CREATE PUBLIC SYNONYM BILLING FOR BILLING;
*/
